- name: list out currnet PV
  shell: pvs --noheadings -o pv_name
  register: pvs_list
 
- debug: var=pvs_list.stdout

- name: create partition on the given disk name
  shell: /bin/echo -e "n\np\n1\n\n\nt\n8e\nw" | fdisk "{{ disk_name }}" ## Create the partition on a disk.
  register: partitioning
  when: pvs_list.stdout | regex_search  '^{{ disk_name }}' 

- debug: var=partitioning
#- debug: var=partitioning.stdout.split('\n\n')

#- set_fact:
#    part: "{{ partitioning.stdout|to_json }}"

#- debug:
    #var: part.split('\n\n\n')
